USE CSE_B_312

--Part – A:
--1. Find all persons with their department name & code.
SELECT *
FROM PERSON
JOIN DEPARTMENT
ON PERSON.D_ID = DEPARTMENT.D_ID

--2. Find the person's name whose department is in C-Block.
SELECT PERSON.PNAME
FROM PERSON
JOIN DEPARTMENT
ON PERSON.D_ID = DEPARTMENT.D_ID
WHERE DEPARTMENT.LOCATION = 'C-BLOCK'

--3. Retrieve person name, salary & department name who belongs to Jamnagar city.
SELECT PERSON.PNAME, PERSON.SALARY, DEPARTMENT.DNAME
FROM PERSON
JOIN DEPARTMENTT
ON PERSON.D_ID = DEPARTMENT.D_ID
WHERE PERSON.CITY = 'JAMNAGAR'

--4. Retrieve person name, salary & department name who does not belong to Rajkot city.
SELECT PERSON.PNAME, PERSON.SALARY, DEPARTMENT.DNAME
FROM PERSON
JOIN DEPARTMENT
ON PERSON.D_TID = DEPARTMENT.D_ID
WHERE PERSON.CITY <> 'RAJKOT'

--5. Retrieve person’s name of the person who joined the Civil department after 1-Aug-2001.
SELECT *
FROM PERSON
JOIN DEPARTMENT
ON PERSON.D_ID = DEPARTMENT.D_ID
WHERE DEPARTMENT.DNAME = 'CIVIL' AND PERSON.JDATE > '1-8-2001'

--6. Find details of all persons who belong to the computer department.
SELECT *
FROM PERSON
JOIN DEPARTMENT
ON PERSON.D_ID = DEPARTMENT.D_ID
WHERE DEPARTMENT.DNAME = 'COMPUTER'

--7. Display all the person's name with the department whose joining date difference
--with the current date is more than 365 days.
SELECT *
FROM PERSON
JOIN DEPARTMENT
ON PERSON.D_ID = DEPARTMENT.DNAME
WHERE DATEDIFF(YEAR, GETDATE(), PERSON.JDATE) > 365

--8. Find department wise person counts.
SELECT DEPARTMENT.DNAME,COUNT(PERSON.PERSONID) AS TOTAL_PERSON
FROM PERSON
JOIN DEPARTMENT
ON PERSON.D_ID = DEPARTMENT.D_ID
GROUP BY DEPARTMENT.DNAME

--9. Give department wise maximum & minimum salary with department name.
SELECT DEPARTMENT.DNAME, MAX(PERSON.SALARY) AS MAX_SALARY, MIN(PERSON.SALARY) AS MIN_SALARY
FROM PERSON
JOIN DEPARTMENT
ON PERSON.D_ID = DEPARTMENT.D_ID
GROUP BY DEPARTMENT.DNAME

--10. Find city wise total, average, maximum and minimum salary.
SELECT PERSON.CITY, SUM(PERSON.SALARY) AS TOTAL_SALARY, AVG(PERSON.SALARY) AS AVERAGE_SALARY, MAX(PERSON.SALARY) AS MAX_SALARY, MIN(PERSON.SALARY) AS MIN_SALARY
FROM PERSON
JOIN DEPARTMENT
ON PERSON.D_ID = DEPARTMENT.D_ID
GROUP BY PERSON.CITY

--11. Find the average salary of a person who belongs to Ahmedabad city.
SELECT PERSON.CITY, AVG(PERSON.SALARY) AS AVERAGE_SALARY
FROM PERSON
JOIN DEPARTMENT
ON PERSON.D_ID= DEPARTMENT.D_ID
WHERE PERSON.CITY = 'RAJKOT'
GROUP BY PERSON.CITY

--12. Produce Output Like: <PersonName> lives in <City> and works in <DepartmentName> Department. (In
--single column)
SELECT PERSON.PNAME + 'LIVES IN' + PERSON.CITY + 'AND WORK IN' + DEPT.DEPARTMENTNAME + 'DEPARTMENT'
FROM PERSON
JOIN DEPARTMENT
ON PERSON.D_ID = DEPARTMENT.D_ID

--Part – B:
--1. Produce Output Like: <PersonName> earns <Salary> from <DepartmentName> department monthly. (In
--single column)
--SELECT PERSON.PERSONNAME +'EARNS'+ CAST(PERSON.SALARY AS int) +'FROM'+ DEPT.DEPARTMENTNAME +'DEPARTMENT MONTHLY'
--FROM PERSON
--JOIN DEPT
--ON PERSON.DEPARTMENTID = DEPT.DEPARTMENTID

--2. Find city & department wise total, average & maximum salaries.
SELECT PERSON.CITY, DEPARTMENT.DNAME, SUM(PERSON.SALARY) AS TOTAL_SAL, AVG(PERSON.SALARY) AS AVERAGE_SAL, MAX(PERSON.SALARY) AS MAX_SALARY
FROM PERSON
JOIN DEPARTMENT
ON PERSON.D_ID = DEPARTMENT.D_ID
GROUP BY PERSON.CITY, DEPARTMENT.DNAME

--3. Find all persons who do not belong to any department.
SELECT *
FROM PERSON
WHERE PERSON.D_ID IS NULL

--4. Find all departments whose total salary is exceeding 100000.
SELECT DEPARTMENT.DNAME, SUM(PERSON.SALARY) AS TOATL_SALARY
FROM PERSON
JOIN DEPARTMENT
ON PERSON.D_ID = DEPARTMENT.D_ID
GROUP BY DEPARTMENT.DNAME
HAVING SUM(PERSON.SALARY) > 100000

--Part – C:
--1. List all departments who have no person.
SELECT DEPARTMENT.DNAME, COUNT(PERSON.PERSON_ID) AS TOTAL_PERSON
FROM PERSON
JOIN DEPARTMENT
ON PERSON.D_ID = DEPARTMENT.D_ID
GROUP BY DEPARTMENT.DNAME
HAVING COUNT(PERSON.PERSON_ID) = 0

--2. List out department names in which more than two persons are working.
SELECT DEPARTMENT.DNAME
FROM PERSON
JOIN DEPARTMENT
ON PERSON.D_ID = DEPARTMENT.D_ID
WHERE DEPARTMENT.DNAME = (SELECT DEPARTMENT.DNAME
							FROM PERSON
							JOIN DEPARTMENT
							ON PERSON.D_ID = DEPARTMENT.D_ID
							GROUP BY DEPARTMENT.DNAME
							HAVING COUNT(PERSON.PERSON_ID) > 2)

--3. Give a 10% increment in the computer department employee’s salary. (Use Update)
UPDATE PERSON
SET SALARY = (SALARY + 0.1*SALARY)
FROM PERSON
JOIN DEPARTMENT
ON PERSON.D_ID = DEPARTMENT.D_ID
WHERE DEPARTMENT.DNAME = 'COMPUTER'